# Generated by Django 3.2.9 on 2022-10-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_conteststudents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conteststudents',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='conteststudents',
            old_name='student_id',
            new_name='student',
        ),
    ]
