# Generated by Django 3.2.9 on 2022-10-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_auto_20221023_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteststudents',
            name='title',
        ),
        migrations.RemoveField(
            model_name='conteststudents',
            name='visible',
        ),
    ]
