# Generated by Django 3.2.9 on 2022-10-23 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0014_auto_20221023_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteststudents',
            name='contest',
        ),
        migrations.AddField(
            model_name='conteststudents',
            name='contest',
            field=models.ManyToManyField(to='contest.Contest'),
        ),
        migrations.RemoveField(
            model_name='conteststudents',
            name='student',
        ),
        migrations.AddField(
            model_name='conteststudents',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
