# Generated by Django 3.2.9 on 2022-10-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20221023_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='assign_students',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ContestStudents',
        ),
    ]
