# Generated by Django 3.2.9 on 2022-10-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_auto_20221023_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestStudents',
        ),
    ]
