# Generated by Django 3.2.9 on 2022-10-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20180501_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
