# Generated by Django 3.2.9 on 2022-10-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20221012_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='real_name',
        ),
    ]
