# Generated by Django 3.2.9 on 2022-10-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_full_name_user_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
