# Generated by Django 3.2.9 on 2022-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videoinfo_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='video_thumbnail',
        ),
    ]
