# Generated by Django 3.2.9 on 2022-10-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_videoinfo_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='video_thumbnail',
            field=models.FileField(default='/public/avatar/default.png', upload_to=''),
        ),
    ]
