# Generated by Django 3.2.9 on 2022-10-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
